version: '3.0'

services:
  catalog-api:
    container_name: catalog-api
    image: ghcr.io/progmise/catalog-api:main
    restart: always
    links:
      - catalog-api-db
    ports:
      - '8080:8080'

  catalog-api-db:
    container_name: catalog-api-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'flights_catalog'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    ports:
      - '3306:3310'
